import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Providers } from "@/store/storeProvider";
import Link from "next/link";
import ResizeProvider from "./utils/resizeProvider";
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Drawer>
            <Navbar />
              <ResizeProvider> 
            {children}
              </ResizeProvider>
            <Footer />
          </Drawer>
        </body>
      </Providers>
    </html>
  );
}

function Drawer({ children }: { children?: React.ReactNode }) {
  return (
    <div className={"drawer drawer-end "}>
      <input id="my-drawer" type="checkbox" className="drawer-toggle" />
      <div className="drawer-content">
        <label
          htmlFor="my-drawer"
          className=" hidden btn btn-primary drawer-button"
        >
          Open drawer
        </label>
        {children} 
      </div>
      <div className="drawer-side">
        <label
          htmlFor="my-drawer"
          aria-label="close sidebar"
          className="drawer-overlay"
        ></label>
        <ul className="menu bg-base-200 text-base-content min-h-full w-80 p-4">
        
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href='/Projects'>Projects</Link>
          </li>
           <li>
            <Link href='/About'>About</Link>
          </li>
           <li>
            <Link href='/Contact'>Contact</Link>
          </li>
        </ul>
      </div>
    </div>
  );
}
